export const lightWebmail = {
  '--app-container-bg': '#fff',
  '--app-container-bg--screening': '#fff',

  '--flag-txt': '#999',
  '--flag-bg': '#eee',

  '--btn-fav-txt--active': '#ffd200',
  '--btn-fav-txt--active--hover': '#ffd200',

  '--filters-bg': '#e5e5e5',

  '--notification-bell-btn-bg': '#fff',
  '--notification-bell-btn-bg--hover': '#d3d3d3',
  '--notification-bell-btn-txt--primary': '#1e1e1e',
  '--notification-bell-btn-txt--secondary': '#8c8c8c',
  '--notification-bell-btn-counter-bg': '#444',
  '--notification-bell-btn-counter-txt': '#eee',
  '--notification-bell-btn-avatar-bg': '#e5e5e5',
  '--notification-bell-btn-avatar-txt': '#666',

  '--shopping-border': '#e5e5e5',
  '--shopping-bg': '#f2f2f2',
  '--shopping-txt': '#313131',
  '--shopping-txt--secondary': '#6a6a6a',
  '--shopping-link': '#1d8fd0',
  '--shopping-link--hover': '#1770a3',

  '--shopping-btn-bg': '#e5e5e5',
  '--shopping-btn-bg--hover': '#d3d3d3',
  '--shopping-btn-txt': '#313131',

  '--shopping-avatar-border': '#f2f2f2',
  '--shopping-avatar-bg': '#f2f2f2',
  '--shopping-avatar-bg--logo': '#fff',
  '--shopping-avatar-txt': '#787878',

  '--shopping-card-bg': '#fff',

  '--shopping-seller-border': '#fff',
  '--shopping-seller-border--active': '#ffd200',
  '--shopping-seller-bg': '#fff',
  '--shopping-seller-txt': '#6a6a6a',
  '--shopping-seller-txt--active': '#000',
  '--shopping-seller-shadow': 'rgba(0, 0, 0, 0.3)',

  '--shopping-tile-border': '#e5e5e5',
  '--shopping-tile-bg': '#fff',
  '--shopping-tile-bg--highlight': '#ffd200',
  '--shopping-tile-txt': '#313131',
  '--shopping-tile-shadow': 'rgba(0, 0, 0, 0.3)',

  '--shopping-placeholder-bg': '#e5e5e5',

  '--shopping-code-border': '#ccc',
  '--shopping-code-bg': '#f2f2f2',
  '--shopping-code-txt': '#313131',

  '--shopping-aside-bg': '#fff1b2',

  '--readmail-border': '#e5e5e5',
  '--readmail-bg': '#e5e5e5',
  '--readmail-txt--primary': '#000',
  '--readmail-txt--secondary': '#666',
  '--readmail-hr': '#ccc',

  '--readmail-swipe-bg': '#e5e5e5',
  '--readmail-swipe-txt': '#000',
  '--readmail-swipe-shadow': 'rgba(0, 0, 0, 0.3)',

  '--attachment-tile-bg': '#fff',
  '--attachment-tile-bg--hover': '#d3d3d3',
  '--attachment-tile-bg--disabled': '#fff',
  '--attachment-tile-txt': '#000',
  '--attachment-tile-txt--hover': '#000',
  '--attachment-tile-txt--disabled': '#ccc',

  '--schema-border': '#e5e5e5',
  '--schema-border--active': '#ffd200',
  '--schema-bg': '#fff',
  '--schema-bg--secondary': '#e5e5e5',
  '--schema-txt': '#313131',
  '--schema-txt--option': '#606060',
  '--schema-label-bg': '#ffe97f',
  '--schema-label-txt': '#000',
  '--schema-label-txt--brand': '#fff',

  '--schema-item-bg': '#e5e5e5',
  '--schema-item-bg--option': '#e5e5e5',
  '--schema-item-border': '#ccc',
  '--schema-item-icon': '#606060',

  '--cashback-goodie-brand--1': '#1a284d',
  '--cashback-goodie-brand--2': '#ca3b65',
  '--cashback-goodie-brand--3': '#ed93b2',
  '--cashback-goodie-txt': '#fff',
  '--cashback-goodie-txt--hover': '#eee',
  '--cashback-goodie-txt--inverted': '#000',

  '--coupon-mails-list-border': '#e5e5e5',
  '--coupon-mails-list-bg': '#fff',
  '--coupon-mails-list-txt--primary': '#000',
  '--coupon-mails-list-txt--secondary': '#6a6a6a',
  '--coupon-mails-list-avatar-border': '#e5e5e5',
  '--coupon-mails-list-avatar-bg': '#fff',
  '--coupon-mails-list-avatar-bg--loading': '#e5e5e5',
  '--coupon-mails-list-avatar-txt': '#000',

  '--how-it-works-icon-bg': '#cadfff',
  '--how-it-works-icon-bg-2': '#d8cfff',
  '--how-it-works-icon-bg-3': '#ffcbce',
  '--how-it-works-icon-bg-4': '#ffebd4',
  '--how-it-works-step-bg': '#ffd200',

  '--banner-border': '#e5e5e5',
  '--banner-bg': '#fff',
  '--banner-shadow': 'rgba(0, 0, 0, 0.05)',
  '--banner-txt--primary': '#000',
  '--banner-txt--secondary': '#909090',
  '--banner-txt--disabled': '#ccc',
  '--banner-txt--brand--hover': '#00b4ff',
  '--banner-txt--brand--gazeta--hover': '#f3002b',
  '--banner-close-border': 'transparent',
  '--banner-close-border--hover': '#d3d3d3',
  '--banner-close-bg': 'transparent',
  '--banner-close-bg--hover': '#d3d3d3',
  '--banner-close-txt': '#000',
  '--banner-close-txt--hover': '#000',
  '--banner-image-bg': '#f8f8f8',
  '--banner-button-bg--primary': '#ffd200',
  '--banner-button-bg--primary--disabled': '#ddd',
  '--banner-button-bg--primary--hover': '#e5bd00',
  '--banner-button-border--primary': '#ffd200',
  '--banner-button-border--primary--disabled': '#ddd',
  '--banner-button-border--primary--hover': '#e5bd00',
  '--banner-button-txt--primary': '#000',
  '--banner-button-txt--primary--disabled': '#ccc',
  '--banner-button-txt--primary--hover': '#000',
  '--banner-button-bg--secondary': 'transparent',
  '--banner-button-bg--secondary--disabled': 'transparent',
  '--banner-button-bg--secondary--hover': '#d3d3d3',
  '--banner-button-border--secondary': 'transparent',
  '--banner-button-border--secondary--disabled': 'transparent',
  '--banner-button-border--secondary--hover': '#d3d3d3',
  '--banner-button-txt--secondary': '#000',
  '--banner-button-txt--secondary--disabled': '#ccc',
  '--banner-button-txt--secondary--hover': '#000',
  '--banner-button-bg-primary--gazeta': '#f3002b',
  '--banner-button-bg-primary--gazeta--hover': '#c20022',
  '--banner-button-border-primary--gazeta': '#f3002b',
  '--banner-button-border-primary--gazeta--hover': '#c20022',
  '--banner-button-txt-primary--gazeta': '#fff',
  '--banner-button-txt-primary--gazeta--hover': '#fff',
  '--banner-icon-txt': '#fff',
  '--banner-list-bg': '#fff',
  '--banner-progressbar-track-bg': '#e5e5e5',
  '--banner-progressbar-thumb-bg': '#ffd200',
  '--banner-progressbar-thumb-bg--gazeta': '#f3002b',
  '--banner-brand': '#ffd200',
  '--banner-brand--hover': '#e5bd00',
  '--banner-brand--gazeta': '#f3002b',
  '--banner-brand--gazeta--hover': '#c20022',
  '--banner-tile-border': '#e5e5e5',
  '--banner-tile-bg': '#fff',
  '--banner-tile-txt': '#000',

  '--shopping-tab-bg': '#fff',
  '--shopping-tab-border': '#e5e5e5',
  '--shopping-tab-border--active': '#ffd200',
  '--shopping-tab-menu-bg': '#d9d9d9',

  '--order-status-bg--default': '#808080',
  '--order-status-bg--delivered': '#6a6a6a',
  '--order-status-bg--error': '#f3002b',
  '--order-status-bg--pickup': '#6fbe3a',
  '--order-status-bg--processing': '#FFD200',
  '--order-status-bg--transit': '#0076cd',
  '--order-status-txt--default': '#fff',
  '--order-status-txt--processing': '#000',
  '--order-form-bg': 'rgba(255, 210, 0, 0.4)',
  '--order-form-txt': '#000',
  '--order-form-button-bg': '#444',
  '--order-form-button-bg--hover': '#2f2f2f',
  '--order-form-button-border': '#444',
  '--order-form-button-border--hover': '#2f2f2f',
  '--order-form-button-txt': '#eee',
  '--order-form-border': '#000',
  '--order-img-bg': '#fff',

  '--newmail-bg': '#e5e5e5',
  '--newmail-bg--mobile': '#e5e5e5',
  '--newmail-txt': '#222',
  '--newmail-txt--error': '#df0000',
  '--newmail-chip-border': '#3fc9ff',
  '--newmail-chip-border--hover': '#00b4ff',
  '--newmail-chip-border--focus': '#00b4ff',
  '--newmail-chip-bg': '#3fc9ff',
  '--newmail-chip-bg--hover': '#00b4ff',
  '--newmail-chip-bg--focus': '#00b4ff',
  '--newmail-chip-txt': '#fff',
  '--newmail-chip-txt--hover': '#fff',
  '--newmail-chip-txt--focus': '#fff',
  '--newmail-contact-border': '#e5e5e5',
  '--newmail-contact-border--hover': '#e5e5e5',
  '--newmail-contact-border--checked': '#e5e5e5',
  '--newmail-contact-border--disabled': '#e5e5e5',
  '--newmail-contact-border--current': '#ffd200',
  '--newmail-contact-bg': '#fff',
  '--newmail-contact-bg--hover': '#e5e5e5',
  '--newmail-contact-bg--checked': '#f2f2f2',
  '--newmail-contact-bg--disabled': '#fff',
  '--newmail-contact-txt--primary': '#222',
  '--newmail-contact-txt--secondary': '#909090',
  '--newmail-contact-txt--hover': '#222',
  '--newmail-contact-txt--checked': '#909090',
  '--newmail-contact-txt--disabled': '#ccc',
  '--newmail-contact-favorite': '#ffd200',
  '--newmail-overlay-bg': 'rgba(255, 255, 255, 0.5)',

  '--upload-progress-txt': '#222',
  '--upload-progress-track-bg': '#e5e5e5',
  '--upload-progress-value-bg': '#3fc9ff',

  '--list-bg': '#fff',

  '--list-item-border': '#f1f1f1',
  '--list-item-bg': '#fff',
  '--list-item-bg--hover': '#e5e5e5',
  '--list-item-bg--checked': '#ffd200',
  '--list-item-bg--highlight': '#ffd200',
  '--list-item-bg--mailing-marked': '#ffc332',
  '--list-item-txt--primary': '#222',
  '--list-item-txt--primary--checked': '#222',
  '--list-item-txt--primary--unseen': '#222',
  '--list-item-txt--primary--mailing-marked': '#222',
  '--list-item-txt--primary--hover': '#222',
  '--list-item-txt--secondary': '#6a6a6a',
  '--list-item-txt--secondary--checked': '#222',
  '--list-item-txt--secondary--mailing-marked': '#222',
  '--list-item-txt--secondary--hover': '#222',
  '--list-item-txt--favourite--active': '#ffd200',
  '--list-item-shadow': 'rgba(0, 0, 0, 0.3)',
  '--list-item-actions-bg': '#e5e5e5',

  '--list-status-bg--seen--primary': '#ccc',
  '--list-status-bg--seen--secondary': '#e5e5e5',
  '--list-status-bg--unseen': '#222',
  '--list-status-bg--mailing': '#ffb400',
  '--list-status-bg--checked': '#222',
  '--list-status-bg--mailing-marked': '#222',
  '--list-status-txt--seen': '#222',
  '--list-status-txt--unseen': '#eee',
  '--list-status-txt--checked': '#eee',
  '--list-status-txt--mailing-marked': '#eee',
  '--list-status-txt--mailing': '#000',

  '--swipe-bg--primary': '#ffd200',
  '--swipe-bg--secondary': '#e5e5e5',

  '--search-query-bg': '#ffd200',
  '--search-query-bg--checked': '#000',
  '--search-query-txt': '#222',
  '--search-query-txt--checked': '#ffd200',

  '--survey-content-bg': '#fff',
  '--survey-content-txt--primary': '#000',
  '--survey-content-txt--secondary': '#606060',
  '--survey-image-bg': '#fff',
  '--survey-article-bg--main': '#fef5cc',
  '--survey-article-bg--business': '#e6cff9',
  '--survey-article-txt--main': '#000',
  '--survey-article-txt--business': '#000',
  '--survey-article-underline--main': '#ffd200',
  '--survey-article-underline--business': '#840ee1',
};
