import { BIMI_PLACEMENTS } from './constants';

export type BimiPlacement =
  | typeof BIMI_PLACEMENTS.DEFAULT
  | typeof BIMI_PLACEMENTS.NEWSLETTER
  | typeof BIMI_PLACEMENTS.NEWSLETTER_PAGE
  | typeof BIMI_PLACEMENTS.READ_MAIL
  | typeof BIMI_PLACEMENTS.SELLER_USER
  | typeof BIMI_PLACEMENTS.SELLER_DEFAULT
  | typeof BIMI_PLACEMENTS.NEW_MAIL_CONTACT;
