export const KEY = 'interfaceEffects';

export const FETCH_INTERFACE_EFFECTS =
  `${KEY}/FETCH_INTERFACE_EFFECTS` as const;
export const FETCH_INTERFACE_EFFECTS_SUCCESS =
  `${FETCH_INTERFACE_EFFECTS}_SUCCESS` as const;
export const FETCH_INTERFACE_EFFECTS_FAILURE =
  `${FETCH_INTERFACE_EFFECTS}_FAILURE` as const;

export const REMOVE_INTERFACE_EFFECT =
  `${KEY}/REMOVE_INTERFACE_EFFECT` as const;

export const SET_INTERFACE_EFFECTS = `${KEY}/SET_INTERFACE_EFFECTS` as const;
