export const darkCommons = {
  '--scrollbar-track-bg': '#222',
  '--scrollbar-track-bg--constant': '#f2f2f2',
  '--scrollbar-thumb-bg': '#444',
  '--scrollbar-thumb-bg--constant': '#ccc',
  '--scrollbar-thumb-bg--hover': '#666',
  '--scrollbar-thumb-bg--hover--constant': '#bbb',

  '--selection-bg': '#006ebd',
  '--selection-txt': '#eee',

  '--focus-border--primary': '#ffd200',
  '--focus-border--secondary': '#000',

  '--tap-bg': 'rgba(0, 110, 189, 0.3)',

  '--social': '#3fc9ff',
  '--offers': '#349e0f',
  '--notifications': '#e72a1b',
  '--eprescriptions': '#ed8311',
  '--epayments': '#1450b4',

  '--state-success': '#96bd31',
  '--state-success--hover': '#789727',
  '--state-success-txt': '#fff',
  '--state-error': '#df0000',
  '--state-error--hover': '#b20000',
  '--state-error-txt': '#fff',
  '--state-warning': '#fed207',
  '--state-warning--hover': '#cfab00',
  '--state-warning-txt': '#1e1e1e',
  '--state-info': '#eee',
  '--state-info--hover': '#bebebe',
  '--state-info-txt': '#1e1e1e',
  '--state-promo-1': '#eee',
  '--state-promo-1--hover': '#bebebe',
  '--state-promo-1-txt': '#1e1e1e',

  '--app-error-bg': '#fff',
  '--app-error-txt': '#313131',

  '--app-bg': '#111',
  '--app-txt': '#aaa',
  '--app-txt--secondary': '#666',
  '--app-txt--option': '#444',
  '--app-image-url': 'url()',

  '--overlay-bg': 'rgba(0, 0, 0, 0.5)',

  '--navbar-bg': '#222',
  '--navbar-txt': '#eee',
  '--navbar-txt--disabled': 'rgba(255, 255, 255, 0.3)',

  '--self-promo-border--secondary': '#444',
  '--self-promo-border--secondary--hover': '#666',
  '--self-promo-bg--secondary': '#444',
  '--self-promo-bg--secondary--hover': '#666',
  '--self-promo-txt--secondary': '#fff',
  '--self-promo-txt--secondary--hover': '#fff',
  '--self-promo-counter-bg--primary': '#fff',
  '--self-promo-counter-txt--primary': '#000',
  '--self-promo-badge-bg--primary': '#222',
  '--self-promo-badge-txt--primary': '#eee',

  '--search-bg': '#fff',
  '--search-txt': '#000',
  '--search-txt--placeholder': '#ccc',

  '--user-avatar-border': '#333',
  '--user-avatar-bg': '#333',
  '--user-avatar-txt': '#eee',
  '--user-avatar-shadow': '#333',

  '--sidebar-bg': '#1e1e1e',
  '--sidebar-btn-txt': 'rgba(255, 255, 255, 0.3)',
  '--sidebar-btn-txt--hover': '#fff',
  '--sidebar-btn-txt--active': '#fff',
  '--sidebar-btn-bg--hover': '#333',

  '--side-menu-bg': '#111',
  '--side-menu-bg--mobile': '#111',
  '--side-menu-line': '#333',
  '--side-menu-shadow--mobile': 'rgba(0, 0, 0, 0.3)',

  '--side-menu-item-bg': 'transparent',
  '--side-menu-item-bg--hover': 'inherit',
  '--side-menu-item-bg--active': '#222',
  '--side-menu-item-bg--disabled': 'inherit',
  '--side-menu-item-txt--primary': '#bbb',
  '--side-menu-item-txt--secondary': '#999',
  '--side-menu-item-txt--hover': '#0076cd',
  '--side-menu-item-txt--active': '#eee',
  '--side-menu-item-txt--disabled': '#666',
  '--side-menu-item-txt--error': '#df0000',

  '--side-menu-counter-bg': '#333',
  '--side-menu-counter-txt': '#fff',

  '--side-menu-badge-txt': '#fff',

  '--cta-primary-border--disabled': 'transparent',
  '--cta-primary-bg--disabled': 'transparent',
  '--cta-primary-txt--disabled': '#444',

  '--cta-secondary-border': 'transparent',
  '--cta-secondary-border--hover': '#3e3e3e',
  '--cta-secondary-border--disabled': 'transparent',
  '--cta-secondary-border--active': '#000',
  '--cta-secondary-bg': 'transparent',
  '--cta-secondary-bg--hover': '#3e3e3e',
  '--cta-secondary-bg--disabled': 'transparent',
  '--cta-secondary-bg--active': '#000',
  '--cta-secondary-txt': '#aaa',
  '--cta-secondary-txt--hover': '#aaa',
  '--cta-secondary-txt--disabled': '#444',
  '--cta-secondary-txt--active': '#aaa',

  '--cta-secondary-neutral-border': 'transparent',
  '--cta-secondary-neutral-border--hover': '#d3d3d3',
  '--cta-secondary-neutral-border--disabled': 'transparent',
  '--cta-secondary-neutral-border--active': '#d3d3d3',
  '--cta-secondary-neutral-bg': 'transparent',
  '--cta-secondary-neutral-bg--hover': '#d3d3d3',
  '--cta-secondary-neutral-bg--disabled': 'transparent',
  '--cta-secondary-neutral-bg--active': '#d3d3d3',
  '--cta-secondary-neutral-txt': '#222',
  '--cta-secondary-neutral-txt--hover': '#222',
  '--cta-secondary-neutral-txt--disabled': '#ccc',
  '--cta-secondary-neutral-txt--active': '#222',

  '--cta-toolbar-submenu-border': 'transparent',
  '--cta-toolbar-submenu-border--hover': '#444',
  '--cta-toolbar-submenu-border--disabled': 'transparent',
  '--cta-toolbar-submenu-border--active': '#000',
  '--cta-toolbar-submenu-bg': 'transparent',
  '--cta-toolbar-submenu-bg--hover': '#444',
  '--cta-toolbar-submenu-bg--disabled': 'transparent',
  '--cta-toolbar-submenu-bg--active': '#000',
  '--cta-toolbar-submenu-txt': '#eee',
  '--cta-toolbar-submenu-txt--hover': '#eee',
  '--cta-toolbar-submenu-txt--disabled': '#444',
  '--cta-toolbar-submenu-txt--active': '#eee',

  '--cta-infobar-border': 'transparent',
  '--cta-infobar-border--hover': '#bebebe',
  '--cta-infobar-border--disabled': 'transparent',
  '--cta-infobar-border--active': '#ccc',
  '--cta-infobar-bg': 'transparent',
  '--cta-infobar-bg--hover': '#bebebe',
  '--cta-infobar-bg--disabled': 'transparent',
  '--cta-infobar-bg--active': '#ccc',
  '--cta-infobar-txt': '#1e1e1e',
  '--cta-infobar-txt--hover': '#1e1e1e',
  '--cta-infobar-txt--disabled': '#aaa',
  '--cta-infobar-txt--active': '#1e1e1e',

  '--cta-navbar-border': 'transparent',
  '--cta-navbar-border--hover': '#444',
  '--cta-navbar-border--disabled': 'transparent',
  '--cta-navbar-border--active': '#000',
  '--cta-navbar-bg': 'transparent',
  '--cta-navbar-bg--hover': '#444',
  '--cta-navbar-bg--disabled': 'transparent',
  '--cta-navbar-bg--active': '#000',
  '--cta-navbar-txt': '#eee',
  '--cta-navbar-txt--hover': '#eee',
  '--cta-navbar-txt--disabled': '#666',
  '--cta-navbar-txt--active': '#eee',

  '--cta-default-border': '#444',
  '--cta-default-border--hover': '#222',
  '--cta-default-border--disabled': 'transparent',
  '--cta-default-bg': '#444',
  '--cta-default-bg--hover': '#222',
  '--cta-default-bg--disabled': 'transparent',
  '--cta-default-txt': '#aaa',
  '--cta-default-txt--hover': '#aaa',
  '--cta-default-txt--disabled': '#444',

  '--cta-default-neutral-border': '#d3d3d3',
  '--cta-default-neutral-border--hover': '#d3d3d3',
  '--cta-default-neutral-border--disabled': 'transparent',
  '--cta-default-neutral-bg': '#fff',
  '--cta-default-neutral-bg--hover': '#d3d3d3',
  '--cta-default-neutral-bg--disabled': 'transparent',
  '--cta-default-neutral-txt': '#222',
  '--cta-default-neutral-txt--hover': '#222',
  '--cta-default-neutral-txt--disabled': '#ccc',

  '--cta-error-border': 'transparent',
  '--cta-error-border--hover': '#fdd8d8',
  '--cta-error-border--disabled': 'transparent',
  '--cta-error-border--active': '#fab1b1',
  '--cta-error-bg': 'transparent',
  '--cta-error-bg--hover': '#fdd8d8',
  '--cta-error-bg--disabled': 'transparent',
  '--cta-error-bg--active': '#fab1b1',
  '--cta-error-txt': '#df0000',
  '--cta-error-txt--hover': '#df0000',
  '--cta-error-txt--disabled': '#fab1b1',
  '--cta-error-txt--active': '#df0000',

  '--cta-field-border': '#111',
  '--cta-field-border--hover': '#222',
  '--cta-field-border--disabled': '#444',
  '--cta-field-border--active': '#444',
  '--cta-field-bg': '#333',
  '--cta-field-bg--hover': '#333',
  '--cta-field-bg--disabled': '#333',
  '--cta-field-bg--active': '#444',
  '--cta-field-txt': '#aaa',
  '--cta-field-txt--hover': '#aaa',
  '--cta-field-txt--disabled': '#444',
  '--cta-field-txt--active': '#aaa',

  '--cta-sidebar-border': 'transparent',
  '--cta-sidebar-border--hover': '#333',
  '--cta-sidebar-border--disabled': 'transparent',
  '--cta-sidebar-border--active': 'transparent',
  '--cta-sidebar-bg': 'transparent',
  '--cta-sidebar-bg--hover': '#333',
  '--cta-sidebar-bg--disabled': 'transparent',
  '--cta-sidebar-bg--active': 'transparent',
  '--cta-sidebar-txt': 'rgba(255, 255,2 55, 0.3)',
  '--cta-sidebar-txt--hover': '#fff',
  '--cta-sidebar-txt--disabled': 'rgba(255, 255, 255, 0.1)',
  '--cta-sidebar-txt--active': '#fff',

  '--cta-onet-premium-border': '#0059b9',
  '--cta-onet-premium-border--hover': '#0050a6',
  '--cta-onet-premium-border--disabled': 'transparent',
  '--cta-onet-premium-border--active': '#0078fa',
  '--cta-onet-premium-bg': '#0059b9',
  '--cta-onet-premium-bg--hover': '#0050a6',
  '--cta-onet-premium-bg--disabled': 'transparent',
  '--cta-onet-premium-bg--active': '#0078fa',
  '--cta-onet-premium-txt': '#fff',
  '--cta-onet-premium-txt--hover': '#fff',
  '--cta-onet-premium-txt--disabled': '#ccc',
  '--cta-onet-premium-txt--active': '#fff',

  '--cta-filter-advanced-border': '#3a3a3a',
  '--cta-filter-advanced-border--hover': '#4a4a4a',
  '--cta-filter-advanced-border--active': '#999',
  '--cta-filter-advanced-border--disabled': '#444',
  '--cta-filter-advanced-bg': '#3a3a3a',
  '--cta-filter-advanced-bg--hover': '#4a4a4a',
  '--cta-filter-advanced-bg--active': '#999',
  '--cta-filter-advanced-bg--disabled': 'transparent',
  '--cta-filter-advanced-txt': '#999',
  '--cta-filter-advanced-txt--hover': '#999',
  '--cta-filter-advanced-txt--active': '#3a3a3a',
  '--cta-filter-advanced-txt--disabled': '#444',

  '--tab-border': 'transparent',
  '--tab-border--hover': '#3e3e3e',
  '--tab-border--disabled': 'transparent',
  '--tab-bg': 'transparent',
  '--tab-bg--hover': '#3e3e3e',
  '--tab-bg--disabled': 'transparent',
  '--tab-txt': '#999',
  '--tab-txt--hover': '#999',
  '--tab-txt--disabled': '#444',

  '--input-border': '#111',
  '--input-border--error': '#df0000',
  '--input-bg': '#333',
  '--input-bg--error': '#333',
  '--input-txt': '#aaa',
  '--input-txt--disabled': '#444',
  '--input-txt--error': '#df0000',

  '--field-label-txt': '#aaa',

  '--context-menu-bg': '#2a2a2a',
  '--context-menu-bg--brand': '#006ebd',
  '--context-menu-border': '#2a2a2a',
  '--context-menu-border--brand': '#006ebd',
  '--context-menu-hr': '#444',
  '--context-menu-shadow': 'rgba(0, 0, 0, 0.3)',
  '--context-menu-txt': '#aaa',
  '--context-menu-txt--secondary': '#777',
  '--context-menu-txt--brand': '#fff',
  '--context-menu-txt--disabled': '#666',
  '--context-menu-txt--error': '#df0000',

  '--group-action-button-txt': '#aaa',
  '--group-action-button-txt--option': '#999',
  '--group-action-button-txt--hover': '#aaa',
  '--group-action-button-txt--disabled': '#666',
  '--group-action-button-bg--hover': '#444',
  '--group-action-button-bg--active': '#1a1a1a',
  '--group-action-button-border--hover': '#444',
  '--group-action-button-border--active': '#1a1a1a',

  '--checkbox-border': '#bbb',
  '--checkbox-border--disabled': '#444',
  '--checkbox-bg': '#333',
  '--checkbox-bg--disabled': '#333',
  '--checkbox-txt': '#aaa',
  '--checkbox-txt--disabled': '#444',

  '--toolbar-bg': '#1e1e1e',
  '--toolbar-bg--moving': '#1e1e1e',
  '--toolbar-bg--mobile': '#1e1e1e',
  '--toolbar-bg--mobile--hover': '#2e2e2e',
  '--toolbar-bg--neutral': '#e5e5e5',
  '--toolbar-txt': '#aaa',
  '--toolbar-txt--mobile': '#aaa',
  '--toolbar-txt--mobile--hover': '#aaa',
  '--toolbar-shadow': 'rgba(0, 0, 0, 0.3)',

  '--infobar-bg': '#dedede',
  '--infobar-txt': '#1e1e1e',
  '--infobar-txt--disabled': '#999',

  '--history-header-bg': '#1e1e1e',

  '--loader-dot-bg': '#aaa',

  '--fetching-message-bg': '#006ebd',
  '--fetching-message-txt': '#eee',
  '--fetching-message-shadow': 'rgba(0, 0, 0, 0.3)',

  '--footer-txt': '#aaa',
  '--footer-txt--hover': '#006ebd',

  '--modal-bg': '#2a2a2a',
  '--modal-txt': '#aaa',
  '--modal-shadow': 'rgba(0, 0, 0, 0.3)',
  '--modal-line': '#444',

  '--weather-widget-bg': 'rgba(0, 0, 0, 0.3)',

  '--box-bg': '#1e1e1e',

  '--iframe-bg': '#fff',

  '--counter-txt': '#eee',

  '--error-txt': '#df0000',
  '--error-border': '#df0000',
  '--error-bg': '#fddfdf',

  '--notification-bg': '#eee',
  '--notification-txt': '#1e1e1e',
  '--notification-txt--disabled': '#999',
  '--notification-shadow': 'rgba(0, 0, 0, 0.3)',
  '--notification-close-bg': '#eee',
  '--notification-close-bg--hover': '#d3d3d3',
  '--notification-close-txt': '#1e1e1e',
  '--notification-close-txt--hover': '#1e1e1e',
  '--notification-progress-bg': '#1e1e1e',

  '--ad-plug-bg': '#1e1e1e',
  '--ad-plug-txt': '#888',

  '--cta-bottom-nav-shadow': 'rgba(0, 0, 0, 0.16)',
  '--ad-block-border--primary': '#f4f3f1',
  '--ad-block-border--secondary': '#fff3b9',
  '--ad-block-border--tertiary': '#fff',
  '--ad-block-bg--primary': '#f4f3f1',
  '--ad-block-bg--secondary': '#fff3b9',
  '--ad-block-bg--tertiary': '#fff',
  '--ad-block-txt--primary': '#1e1e1e',
  '--ad-block-txt--secondary': '#1e1e1e',
  '--ad-block-txt--tertiary': '#1e1e1e',
  '--ad-block-decoration': '#ffd200',
  '--ad-block-decoration--hover': '#e5bd00',

  '--cta-botton-nav-shadow': 'rgba(0, 0, 0, 0.16)',

  '--bimi-border--readmail': '#444',
  '--bimi-bg--readmail': '#333',
  '--bimi-txt--readmail': '#aaa',

  '--bimi-border--newmail': '#006ebd',
  '--bimi-border--newmail--checked': '#2a2a2a',
  '--bimi-bg--newmail': '#006ebd',
  '--bimi-bg--newmail--checked': '#2a2a2a',
  '--bimi-txt--newmail': '#eee',
  '--bimi-txt--newmail--checked': '#444',

  '--editor-border': '#111',
  '--editor-bg': '#fff',
  '--editor-toolbar-border': '#111',
  '--editor-toolbar-bg': '#333',
  '--editor-img-border': '#88bffe',
  '--editor-img-btn-bg': '#4099ff',
  '--editor-img-btn-bg--hover': '#0076ff',
  '--editor-img-btn-border': '#4099ff',
  '--editor-img-btn-border--hover': '#0076ff',
  '--editor-img-btn-txt': '#fff',
  '--editor-img-btn-shadow': 'rgba(0, 0, 0, 0.3)',
  '--editor-btn-selected-color-shadow': '#111',

  '--component-state-txt--primary': '#aaa',
  '--component-state-txt--secondary': '#999',
  '--component-state-link': '#aaa',
};
