export const notificationMockup = {
  onetkonto_password_is_leaked: [
    {
      nid: 1,
      ctime: '1729606834',
      redirect_url: 'https://google.pl',
      processing_state: 'SENT',
      notification_type_id: 'onetkonto_password_is_leaked',
    },
    {
      nid: 10,
      ctime: '1729606835',
      redirect_url: 'https://google.pl',
      processing_state: 'READ',
      notification_type_id: 'onetkonto_password_is_leaked',
    },
    {
      nid: 13,
      ctime: '1729606836',
      redirect_url: 'https://google.pl',
      processing_state: 'READ',
      notification_type_id: 'onetkonto_password_is_leaked',
    },
    {
      nid: 16,
      ctime: '1729606837',
      redirect_url: 'https://google.pl',
      processing_state: 'READ',
      notification_type_id: 'onetkonto_password_is_leaked',
    },
  ],
  onetkonto_contact_data_changed: [
    {
      nid: 2,
      ctime: '1729606838',
      redirect_url: 'https://google.pl',
      processing_state: 'READ',
      notification_type_id: 'onetkonto_contact_data_changed',
    },
    {
      nid: 5,
      ctime: '1729606839',
      redirect_url: 'https://google.pl',
      processing_state: 'SENT',
      notification_type_id: 'onetkonto_contact_data_changed',
    },
    {
      nid: 11,
      ctime: '1729606840',
      redirect_url: 'https://google.pl',
      processing_state: 'READ',
      notification_type_id: 'onetkonto_contact_data_changed',
    },
    {
      nid: 14,
      ctime: '1729606841',
      redirect_url: 'https://google.pl',
      processing_state: 'SENT',
      notification_type_id: 'onetkonto_contact_data_changed',
    },
    {
      nid: 15,
      ctime: '1729606842',
      redirect_url: 'https://google.pl',
      processing_state: 'SENT',
      notification_type_id: 'onetkonto_contact_data_changed',
    },
  ],
  onetkonto_profile_data_changed: [
    {
      nid: 3,
      ctime: '1729606843',
      redirect_url: 'https://google.pl',
      processing_state: 'SENT',
      notification_type_id: 'onetkonto_profile_data_changed',
    },
    {
      nid: 6,
      ctime: '1729606844',
      redirect_url: 'https://google.pl',
      processing_state: 'READ',
      notification_type_id: 'onetkonto_profile_data_changed',
    },
    {
      nid: 7,
      ctime: '1729606845',
      redirect_url: 'https://google.pl',
      processing_state: 'SENT',
      notification_type_id: 'onetkonto_profile_data_changed',
    },
    {
      nid: 9,
      ctime: '1729606846',
      redirect_url: 'https://google.pl',
      processing_state: 'READ',
      notification_type_id: 'onetkonto_profile_data_changed',
    },
  ],
  onetkonto_wellcome: [
    {
      nid: 8,
      ctime: '1729606847',
      redirect_url: 'https://google.pl',
      processing_state: 'SENT',
      notification_type_id: 'onetkonto_wellcome',
    },
  ],
  onetkonto_new_device_login: [
    {
      nid: 4,
      ctime: '1729606848',
      redirect_url: 'https://google.pl',
      processing_state: 'READ',
      notification_type_id: 'onetkonto_new_device_login',
    },
    {
      nid: 12,
      ctime: '1729606849',
      redirect_url: 'https://google.pl',
      processing_state: 'SENT',
      notification_type_id: 'onetkonto_new_device_login',
    },
  ],
  onetkonto_password_changed: [
    {
      nid: 16,
      ctime: '1729606850',
      redirect_url: 'https://google.pl',
      processing_state: 'SENT',
      notification_type_id: 'onetkonto_password_changed',
    },
  ],
};
